"""initial migration

Revision ID: 47ee85e135c6
Revises: 
Create Date: 2024-09-03 16:46:10.875016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ee85e135c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_index(op.f('ix_service_title'), 'service', ['title'], unique=False)
    op.create_table('social_network',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_network_id'), 'social_network', ['id'], unique=False)
    op.create_index(op.f('ix_social_network_title'), 'social_network', ['title'], unique=False)
    op.create_table('tecnologia',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnologia_id'), 'tecnologia', ['id'], unique=False)
    op.create_index(op.f('ix_tecnologia_title'), 'tecnologia', ['title'], unique=False)
    op.create_table('images_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_products_id'), 'images_products', ['id'], unique=False)
    op.create_index(op.f('ix_images_products_url'), 'images_products', ['url'], unique=False)
    op.create_table('images_service',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_service_id'), 'images_service', ['id'], unique=False)
    op.create_index(op.f('ix_images_service_url'), 'images_service', ['url'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('intermediaria_user_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('products_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intermediaria_user_products_id'), 'intermediaria_user_products', ['id'], unique=False)
    op.create_table('intermediaria_user_services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intermediaria_user_services_id'), 'intermediaria_user_services', ['id'], unique=False)
    op.create_table('user_social_network',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('social_network_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['social_network_id'], ['social_network.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_social_network_id'), 'user_social_network', ['id'], unique=False)
    op.create_table('user_tecnologia',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tecnologia_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tecnologia_id'], ['tecnologia.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tecnologia_id'), 'user_tecnologia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tecnologia_id'), table_name='user_tecnologia')
    op.drop_table('user_tecnologia')
    op.drop_index(op.f('ix_user_social_network_id'), table_name='user_social_network')
    op.drop_table('user_social_network')
    op.drop_index(op.f('ix_intermediaria_user_services_id'), table_name='intermediaria_user_services')
    op.drop_table('intermediaria_user_services')
    op.drop_index(op.f('ix_intermediaria_user_products_id'), table_name='intermediaria_user_products')
    op.drop_table('intermediaria_user_products')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_images_service_url'), table_name='images_service')
    op.drop_index(op.f('ix_images_service_id'), table_name='images_service')
    op.drop_table('images_service')
    op.drop_index(op.f('ix_images_products_url'), table_name='images_products')
    op.drop_index(op.f('ix_images_products_id'), table_name='images_products')
    op.drop_table('images_products')
    op.drop_index(op.f('ix_tecnologia_title'), table_name='tecnologia')
    op.drop_index(op.f('ix_tecnologia_id'), table_name='tecnologia')
    op.drop_table('tecnologia')
    op.drop_index(op.f('ix_social_network_title'), table_name='social_network')
    op.drop_index(op.f('ix_social_network_id'), table_name='social_network')
    op.drop_table('social_network')
    op.drop_index(op.f('ix_service_title'), table_name='service')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_table('role')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
